### ISSUE TITLE
NullPointerException in GooglePayHandler.java:30 

### ISSUE THREAD

**Issue by asaarnak** [google-pay/flutter-plugin#196]
Has happened for 3 users since March 28.
We have used latest `pay` and latest `flutter` version.
Users had different Android versions 11, 12 and 13.
```stacktrace
Caused by java.lang.NullPointerException:
       at io.flutter.plugins.pay_android.GooglePayHandler.onActivityResult(GooglePayHandler.java:30)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:13)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:5)
       at android.app.Activity.dispatchActivityResult(Activity.java:8471)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5507)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5553)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8210)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by JlUgia** [comment]
Good day @asaarnak.
Take a look at the patches release for `pay_android` and `pay`. They may resolve the issue.
See #206 for context.

**Comment by JlUgia** [comment]
I'm closing this issue.
If the NPE persist, feel free to add to #206.
