### ISSUE TITLE
[pay_android] GooglePayHandler.onActivityResult - lateinit property loadPaymentDataResult has not been initialized

### ISSUE THREAD

**Issue by aleksandr-kopenkov-idf** [google-pay/flutter-plugin#206]
This crash affects some users of Redmi devices. 
Users have different versions of Android (10 - 12).
pay version: 1.1.1

```
Caused by kotlin.UninitializedPropertyAccessException: lateinit property loadPaymentDataResult has not been initialized
       at io.flutter.plugins.pay_android.GooglePayHandler.handlePaymentSuccess(GooglePayHandler.kt:216)
       at io.flutter.plugins.pay_android.GooglePayHandler.onActivityResult(GooglePayHandler.kt:180)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:964)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:566)
       at android.app.Activity.dispatchActivityResult(Activity.java:8381)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5334)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5380)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2247)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7886)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by maxim-ivanchuk-idf** [comment]
Same problem!

**Comment by TaN4eLL0** [comment]
Hello, our users have the same problem. 
Please, urgently deal with this!

**Comment by pandeykushal** [comment]
hi did you had an issue with the real device

**Comment by JlUgia** [comment]
Thank you for reporting.
This seems to be related with the application/activity being collected by the system and calling onActivityResult on top of an obsolete/inexistent instance. Does that sound like something that could be happening on those RedMi devices?

I've pushed an update to the `pay_android` package (to 1.0.11), and `pay` package (to 1.1.2), that removes the activity result listener when the activity is disconnected. If the hypothesis is accurate, this update may fix the issue.
Please update the thread with the result of your tests @pandeykushal @TaN4eLL0 @maxim-ivanchuk-idf @aleksandr-kopenkov-idf

**Comment by aleksandr-kopenkov-idf** [comment]
@JlUgia  
Thanks for the update

**Comment by JlUgia** [comment]
Closing this issue for now.
Feel free to re-open if the underlying problem is not resolved.

**Comment by ekaterina-demeshko-idf** [comment]
Hello @JlUgia, we still have crushes after updating pay to `1.1.2`
 
 Devices Xiomi, Android 12:
```

Caused by java.lang.NullPointerException:
       at io.flutter.plugins.pay_android.GooglePayHandler.onActivityResult(GooglePayHandler.kt:186)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:813)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:868)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:1251)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:691)
       at android.app.Activity.dispatchActivityResult(Activity.java:8564)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5455)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4904)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4950)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8309)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```
       
       
 And for Samsung, Huawei (Android 13 and 10):

       Caused by java.lang.NullPointerException:
       at io.flutter.plugins.pay_android.GooglePayHandler.handlePaymentSuccess(GooglePayHandler.kt:216)
       at io.flutter.plugins.pay_android.GooglePayHandler.onActivityResult(GooglePayHandler.kt:180)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:813)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:868)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:1251)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:691)
       at android.app.Activity.dispatchActivityResult(Activity.java:8541)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5775)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by stephenmcd** [comment]
Should be fixed in e2cb844
