### ISSUE TITLE
Unable to invoke Google Pay using `_pay.showPaymentSelector`

### ISSUE THREAD

**Issue by awazgyawali** [google-pay/flutter-plugin#45]
I am facing native crash when I am trying to make a payment using google pay and stripe as tokenizer.  The error I get is

```
E/MethodChannel#plugins.flutter.io/pay_channel: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.putOpt(java.lang.String, java.lang.Object)' on a null object reference
        at io.flutter.plugins.pay_android.GooglePayHandler$Companion.buildPaymentProfile(GooglePayHandler.kt:53)
        at io.flutter.plugins.pay_android.GooglePayHandler.loadPaymentData(GooglePayHandler.kt:98)
        at io.flutter.plugins.pay_android.PayMethodCallHandler.onMethodCall(PayMethodCallHandler.kt:66)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
        
        
Seems when we actually try to make a payment, there is no `transactionInfo` object on the payment profile where as https://github.com/google-pay/flutter-plugin/blob/66c5cdebdf70e3a4a364f74586b1f8915fbbf3ee/pay_android/android/src/main/kotlin/io/flutter/plugins/pay_android/GooglePayHandler.kt#L52 wants to inject amount inside `transactionInfo`

**Comment by awazgyawali** [comment]
Just for reference, this is my profile 

```
{
  "provider": "google_pay",
  "data": {
    "environment": "TEST",
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
      {
        "type": "CARD",
        "tokenizationSpecification": {
          "type": "PAYMENT_GATEWAY",
          "parameters": {
            "gateway": "stripe",
            "stripe:version": "2020-08-27",
            "stripe:publishableKey":  "<TOKEN>"
          }
        },
        "parameters": {
          "allowedCardNetworks": [
            "VISA",
            "MASTERCARD"
          ],
          "allowedAuthMethods": [
            "PAN_ONLY",
            "CRYPTOGRAM_3DS"
          ],
          "billingAddressRequired": false
        }
      }
    ],
    "merchantInfo": {
      "merchantId": "BCR2DN6T5624DX32",
      "merchantName": "ThePension"
    },
    "transactionInfo": {
      "countryCode": "FR",
      "currencyCode": "EUR"
    }
  }
}
```

**Comment by JlUgia** [comment]
Hi @awazgyawali.
I've tried a few things, but none seem to get close to what you are seeing. I can only reproduce the issue when I intentionally remove the `transactionInfo` block from the configuration.
Can you verify that you are loading the right configuration resource?

**Comment by awazgyawali** [comment]
@JlUgia Yet again, its my fault and probably is always going to be. 

This might the solution to other devs facing the same issue. The solution is, do not send apple_pay as the provider parameter when you want to invoke google pay on android.

**Comment by JlUgia** [comment]
That's right, the provider and configuration need to be consistent.
If there are configuration mistakes, that means that there's room for improvement.
Thank you for the feedback!
