### ISSUE TITLE
Issues migrating from stripe_payment to flutter_stripe. "Unexpected Error, try again" without giving more details

### ISSUE THREAD

**Issue by danielo17** [google-pay/flutter-plugin#95]
Hello, 

As indicated in the former discontinued "stripe_payment" plugin, I migrated my app to "flutter_stripe" + "pay". At the moment of writing on their last versions. Here my Pubspec.yaml:

```
  flutter_stripe: ^1.3.0
  pay: ^1.0.5
```
I have problems with Apple Pay. Here is what I do.
First I initialize both plugging when running main():

```
    _payClient = Pay.withAssets([
      'apple_pay_payment_profile.json',
      'google_pay_payment_profile.json'
    ]);
    Stripe.publishableKey = _stripeClavePublica;
    Stripe.merchantIdentifier = ConfigSave.merchantAppleStore;
    Stripe.urlScheme = 'xxxx';
    await Stripe.instance.applySettings();
```

apple_pay_payment_profile.json looks something like:

```
{
  "provider": "apple_pay",
  "data": {
    "merchantIdentifier": "myMerchant",
    "displayName": "MyCompanyName",
    "merchantCapabilities": ["3DS", "debit", "credit"],
    "supportedNetworks": ["amex", "visa", "discover", "masterCard"],
    "countryCode": "ES",
    "currencyCode": "EUR",
    "requiredBillingContactFields": ["emailAddress", "name", "phoneNumber", "postalAddress"],
    "requiredShippingContactFields": [],
    "shippingMethods": [
      {
        "amount": "0.00",
        "detail": "Available within an hour",
        "identifier": "in_store_pickup",
        "label": "In-Store Pickup"
      },
      {
        "amount": "4.99",
        "detail": "5-8 Business Days",
        "identifier": "flat_rate_shipping_id_2",
        "label": "UPS Ground"
      },
      {
        "amount": "29.99",
        "detail": "1-3 Business Days",
        "identifier": "flat_rate_shipping_id_1",
        "label": "FedEx Priority Mail"
      }
    ]
  }
}
```

And I invoke:

```
     var _paymentItems = [
        PaymentItem(
          label: 'Pagar a MyCompany Servicio X',
          amount: '200',
          status: PaymentItemStatus.final_price,
        )
      ];

      final paymentResult = await _payClient.showPaymentSelector(
        provider: Platform.isIOS?PayProvider.apple_pay:PayProvider.google_pay,
        paymentItems: _paymentItems,
      );
```

This seems to work, both in a simulator and a device, returning the following paymentResult:

```
PAYMENTRESULT: {shippingMethod: null, token: {"version":"EC_v1","data":"loooong key","header":{"ephemeralPublicKey":"someKey","publicKeyHash":"someKey","transactionId":"someID"}}, paymentMethod: {displayName: Visa 8180, type: 2, network: Visa}, billingContact: {name: The Customer, phoneNumber: null, emailAddress: null}, shippingContact: null}
    LOG ANALYTICS: ["event": "stripeios.token_creation", "apple_pay_enabled": 1, "product_usage": [], "publishable_key": "pk_test_51...", "additional_info": [], "apple_merchant_identifier": "unknown", "os_version": "14.5", "shipping_type": "shipping", "bindings_version": "21.7.0", "app_version": "1.0.4", "additional_payment_methods": "none", "token_type": "apple_pay", "device_type": "iPhone10,4", "ocr_type": "none", "analytics_ua": "analytics.stripeios-1.0", "required_billing_address_fields": "zip", "app_name": "save", "company_name": "save", "required_shipping_address_fields": "none", "ui_usage_level": "none"]
```

Then, when I try to get the token to pass it to my backend, I get a generic exception. Doesn't give much detail:

```
flutter: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: There was an unexpected error -- try again in a few seconds, message: There was an unexpected error -- try again in a few seconds, stripeErrorCode: null, declineCode: null, type: null))
      flutter: #0      ResultParser.parse (package:stripe_platform_interface/src/result_parser.dart:15:7)
      #1      MethodChannelStripe.createApplePayToken (package:stripe_platform_interface/src/method_channel_stripe.dart:279:10)
      <asynchronous suspension>
      #2      Stripe.createApplePayToken (package:flutter_stripe/src/stripe.dart:130:25)
      <asynchronous suspension>
      #3      ServicioPago.pagaNativo (package:save/serviciosProveedores/servicioPago.dart:336:21)
      <asynchronous suspension>
      #4      _SelectorPagoState.pagar (package:save/pages/selectorPago.dart:119:11)
      <asynchronous suspension>
```

The only thing that I see strange is **"apple_merchant_identifier": "unknown"**, where in the json property file, it is set up.

Does anyone has an idea of what is happening?

 Many thanks in advance

**Comment by JlUgia** [comment]
Your payment configuration looks okay to me, assuming you have substituted some of the secret values in your comment.
I'd suggest to create/reference this issue in the [Flutter plugin for Stripe](https://github.com/flutter-stripe/flutter_stripe).
CC'ing @jamesblasco who is involved in its development.

**Comment by danielo17** [comment]
Thank you. I'll create it there. Wasn't sure since the Pay plugin is returning "unknown" where I would expect to see my merchant identifier.
